<a href="https://colab.research.google.com/github/TJ-SIVA/blooddonotion/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a =np.arange(1,10).reshape(3,3)'''arange is function like range function in python range create elements with in given range
arange used to create an array with contnious values in the given range and the we can reshape it into desire shape but number of
elements and size must be compitable '''
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.nbytes)
print(a.real)

2
8
int64
9
72
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b = np.ones([3,3])
a.dot(b)


array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [ ]:
a =np.linspace(50,101,)
a


array([ 50.       ,  50.0000051,  50.0000102, ..., 100.9999898,
       100.9999949, 101.       ])

In [ ]:
c=np.identity(7,dtype="int32")

print(c)
print(c.itemsize)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]
4


In [ ]:
#From [1,2,3,4,5], get elements 2 to 4 using slicing.

arr = np.array([1,2,3,4,5])
print(arr[1:4])

#Replace all odd numbers in an array with -1
arr[arr % 2 == 1 ] =-1
print(arr)

#Reverse a NumPy array without using slicing.

print(np.flipud(arr))

y = np.array([[1,25,6],[3,6,7],[4,7,8]])
print(np.flip(y))

[2 3 4]
[-1  2 -1  4 -1]
[-1  4 -1  2 -1]
[[ 8  7  4]
 [ 7  6  3]
 [ 6 25  1]]


In [ ]:
#Add 5 to every element in an array using broadcasting.
a = np.array([[1,5,67,8],[3,46,32,4]])
b = 5
print(a+b)
print()


#stacking array
b=np.array([[1,2,3,7],[4,5,6,8]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 6 10 72 13]
 [ 8 51 37  9]]

[[ 1  5 67  8]
 [ 3 46 32  4]
 [ 1  2  3  7]
 [ 4  5  6  8]]
[[ 1  5 67  8  1  2  3  7]
 [ 3 46 32  4  4  5  6  8]]


1. Navigation: Robot Path Transformation
Scenario: A robot at position [2, 1] rotates 90° counterclockwise. What's the new position?

In [ ]:
inital_position = np.array([2,1])
theta = np.radians(90)
roatation = np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
new_position = np.dot(roatation,inital_position)
print(f"new_position = {new_position}")

new_position = [-1.  2.]


🧪 PART 3: Code Challenges 🔥
✅ Challenge 1: Invert & Validate
Given matrix A = [[4, 7], [2, 6]]:

Compute inverse.

Multiply A @ A_inv — should be identity.

In [ ]:
a = np.array([[4,7],[2,6]])
a_inv = np.linalg.inv(a)
print(f"inverse = {a_inv}")
print(f"identity = {np.dot(a,a_inv)}")

inverse = [[ 0.6 -0.7]
 [-0.2  0.4]]
identity = [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


✅ Challenge 2: Eigen Check
Use this matrix:

python
Copy
Edit
B = np.array([[3, 1],
              [1, 3]])
Find eigenvalues & eigenvectors

Multiply B @ eigenvector == eigenvalue * eigenvector?

✅ Confirm this property using 1st eigenpair.

In [ ]:
b = np.array([[3,1],[1,3]])
eigenvalues,eigenvectors = np.linalg.eig(b)
print(f"eigenvalues = {eigenvalues}")
print(f"eigenvectors = {eigenvectors}")
print(f"is b@eigenvectoes == egienvalues * eigenvectors{b@eigenvectors==eigenvalues*eigenvectors}")

eigenvalues = [4. 2.]
eigenvectors = [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
is b@eigenvectoes == egienvalues * eigenvectors[[ True  True]
 [ True  True]]


✅ Challenge 3: Cross Product 3D Robot Arm
Given robot arms as vectors:

python
Copy
Edit
a = [1, 0, 0]  # arm 1 along X-axis
b = [0, 1, 0]  # arm 2 along Y-axis
Find perpendicular direction using cross product

Output should be in what direction?

(Hint: Which axis is X × Y?)



In [ ]:
a = np.array([1,0,0])
b = np.array([0,1,0])
c = np.cross(a,b)
print(c)

[0 0 1]


✅ Task: Replace all odd numbers in a NumPy array with -1 (no loop)
Example:
Input:  arr = np.array([1, 2, 3, 4, 5])
Output: [-1  2 -1  4 -1]

In [ ]:
arr = np.array([1,2,3,4,5])
arr[arr % 2 == 1] = -1
print(arr)

[-1  2 -1  4 -1]


Code 2. Create a 3x3 identity matrix, and scale it by 5.

In [ ]:
a = np.identity(3,dtype=np.int32)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

Code 3. Reverse a NumPy array without using slicing.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.flipud(arr))
print(np.flip(arr))


[[4 5 6]
 [1 2 3]]
[[6 5 4]
 [3 2 1]]


Given a matrix, subtract the mean of each row from every element in that row.



In [ ]:
arr = np.arange(6).reshape(2,3)
b = np.mean(arr,axis=1,keepdims = True)
print(arr-b)

[[-1.  0.  1.]
 [-1.  0.  1.]]


🔹 PART 1: Copy vs View — Are You Holding the Same Sword?
🎯 Problem:
python
Copy
Edit
import numpy as np

a = np.array([1, 2, 3])
b = a[1:]    # slicing
b[0] = 99
print(a)
❓ What do you think this will print?



In [ ]:
a =np.arange(3)
print(a)
'''b =a[1:]
print(b)
b[0]=99
print(a)
print(b)'''
b =a[1:].copy()
print(b)
b[0]=99
print(a)
print(b)

[0 1 2]
[1 2]
[0 1 2]
[99  2]


loop vs numpy opretions timeing diffrence are high

In [ ]:
arr =np.random.randint(0,100,size = 1000000)

def add_by_loop(arr):
  return(x+1 for x in arr)
def add_by_numpy(arr):
  return(1+arr)
%timeit add_by_loop(arr)
%timeit add_by_numpy(arr)

688 ns ± 158 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
775 µs ± 69.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


✅ Rule of Broadcasting
NumPy compares dimensions from the end:

Array A	2	3
Array B	1	3

If dimensions match or one is 1, it's OK ✅

Otherwise: ❌ ValueError



In [ ]:
a = np.array([1, 2, 3])   # shape (3,1)
b = np.array([10, 20, 30])      # shape (3,)
b = np.expand_dims(b,axis=1)
print(a+b)
# What will a + b do?
print((a + b).shape)
print(a + b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


✅ Challenge 4: Swap the first and last column in a 2D array
python
Copy
Edit
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(np.fliplr(a))
print(np.diag(np.fliplr(a)))


[[3 2 1]
 [6 5 4]
 [9 8 7]]


✅ Challenge 5: Get the anti-diagonal of a matrix
python
Copy
Edit
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Output: [3 5 7]

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(np.fliplr(a))
print(np.diag(np.fliplr(a)))


✅ Challenge 6: Set all border elements of a 5x5 matrix to 1, rest 0
python
Copy
Edit
a = np.zeros((5, 5), dtype=int)
# Output:
# [[1 1 1 1 1]
#  [1 0 0 0 1]
#  [1 0 0 0 1]
#  [1 0 0 0 1]
#  [1 1 1 1 1]]

In [ ]:
a =np.zeros((5,5),dtype=int)
a[0,:] =1
a[-1,:] =1
a[:,0] =1
a[:,-1] =1
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


✅ Challenge 7: Extract every 2nd row and every 2nd column from a matrix
python
Copy
Edit
a = np.arange(36).reshape(6, 6)
# Output should be a 3x3 matrix


In [ ]:
a =np.arange(36).reshape(6,6)
print(a[0:6:2,0:6:2])


[[ 0  2  4]
 [12 14 16]
 [24 26 28]]


Given a = np.arange(1, 13).reshape(3, 4), compute:

Row-wise sum

Column-wise mean

Global standard deviation

Cumulative sum row-wise



In [ ]:
a = np.arange(1,13).reshape(3,4)
print(f"sum by rows = {np.sum(a,axis=1)}")
print(f" Column-wise mean = {np.mean(a,axis=1)}")
print(f"std = {np.std(a)}")
print(f"Cumulative sum row-wise{np.cumsum(a,axis=1)}")

sum by rows = [10 26 42]
 Column-wise mean = [ 2.5  6.5 10.5]
std = 3.452052529534663
Cumulative sum row-wise[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


🎯 Challenge 2:
Given:

python
Copy
Edit
a = np.array([[3, 7, 5],
              [0, 2, 9],
              [6, 1, 8]])
Answer the following:

In which rows is all elements > 2?

In which columns is any element = 0?

Is every element of the array less than 10?



In [ ]:
a = np.array([[3,7,5],[0,2,9],[6,1,8]])
print(np.all(a>2,axis=1))
print(np.any(a==0,axis=0))
print(np.all(a<10))

[ True False False]
[ True False False]
True


🎯 Challenge 3: Sorting + Ranking
python
Copy
Edit
a = np.array([[15, 3, 7],
              [2, 25, 10],
              [8, 18, 5]])
Answer these:

Sort each row.

Sort each column.

Find the indices that would sort row 1.

Retrieve the ranked values from row 1 using those indices.



In [ ]:


import numpy as np
a = np.array([[15, 3, 7],
              [2, 25, 10],
              [8, 18, 5]])

# Sort each row
print("Sorted rows:")
print(np.sort(a, axis=1))

# Sort each column
print("\nSorted columns:")
print(np.sort(a, axis=0))

# Find the indices that would sort row 1
row1_indices = np.argsort(a[0])
print("\nIndices that sort row 1:")
print(row1_indices)

# Retrieve the ranked values from row 1 using those indices
ranked_row1 = a[0][row1_indices]
print("\nRanked values from row 1:")
ranked_row1

Sorted rows:
[[ 3  7 15]
 [ 2 10 25]
 [ 5  8 18]]

Sorted columns:
[[ 2  3  5]
 [ 8 18  7]
 [15 25 10]]

Indices that sort row 1:
[1 2 0]

Ranked values from row 1:


array([ 3,  7, 15])

**STASTITICS ON NUMPY**


🧪 Challenge Time!
python
Copy
Edit
data = np.array([[5, 10, 15],
                 [20, 25, 30],
                 [35, 40, 45]])
Answer:

Find:

Row-wise mean

Column-wise std

75th percentile of entire data

Get the correlation coefficient of the first row and last row.



In [ ]:
from posixpath import pathsep
a = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(np.mean(a,axis=1))
print(np.std(a,axis=1))
print(np.percentile(a,75))
print(np.corrcoef(a[0],a[-1]))

[10. 25. 40.]
[4.0824829 4.0824829 4.0824829]
35.0
[[1. 1.]
 [1. 1.]]


✅ Challenge 1: Student Scores Matrix
python
Copy
Edit
scores = np.array([
    [85, 90, 92],
    [78, 88, 84],
    [90, 94, 96],
    [70, 65, 60]
])
Answer the following:

Find the mean score for each student (row-wise).

Find the standard deviation for each subject (column-wise).

How many students scored all marks above 80?

Which subject (column) has the highest average score?

What is the median of all scores?

In [ ]:
socres = np.array([[85,90,92],[78,88,84],[90,94,96],[70,65,60]])
print(np.mean(socres,axis=1))
print(np.std(socres,axis=0))
print(np.all(socres > 80,axis=1))
high = np.median(socres,axis=0)
print(np.max(high))
print(np.median(socres))

[89.         83.33333333 93.33333333 65.        ]
[ 7.52911017 11.32199187 13.96424004]
[ True False  True False]
89.0
86.5


✅ Challenge 2: Health Data Matrix
python
Copy
Edit
health = np.array([
    [60, 120],   # [heart rate, systolic BP]
    [72, 110],
    [55, 140],
    [65, 130]
])
Find the mean heart rate and blood pressure.

Use np.all to check if all patients have heart rate > 50.

Use np.any to check if any patient has BP > 135.

Find the correlation coefficient between heart rate and BP.



In [ ]:
health = np.array([[60,120],[72,110],[55,140],[65,130]])
print(np.mean(health[:,0]),np.mean(health[:,1]))
print(np.all(health[:,0]>50))
print(np.any(health[:,1]>135))
print(np.corrcoef(health[0],health[1]))

63.0 125.0
True
True
[[1. 1.]
 [1. 1.]]


✅ Challenge 3: Percentile + Cumulative Tricks
python
Copy
Edit
a = np.random.randint(1, 100, size=(5, 5))
Find the 75th percentile row-wise.

Compute the cumulative sum column-wise.

Count how many elements in a are greater than the median.



In [ ]:
a = np.random.randint(1,100,size=(5,5))
print(a)
print(np.percentile(a,75,axis=1))
print(np.cumsum(a,axis=0))
a_t = a[a > np.mean(a)]
print(np.size(a_t))

[[16 20 18 86 32]
 [46 47 47 35 99]
 [69 44 25 55 68]
 [73  1 56 71 11]
 [17 72 15  7 85]]
[32. 47. 68. 71. 72.]
[[ 16  20  18  86  32]
 [ 62  67  65 121 131]
 [131 111  90 176 199]
 [204 112 146 247 210]
 [221 184 161 254 295]]
13


🎯 CHALLENGE TIME: Linear Ops
Use:

python
Copy
Edit
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
Answer these:

Compute a @ b

Compute the determinant of a

Compute the inverse of a

Verify a @ inv(a) equals identity

What does np.dot(a, a.T) compute?



In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a@b)
print(np.linalg.det(a))
inv_a = np.linalg.inv(a)
print(inv_a)
print(np.identity(2) == np.dot(a,inv_a))
print(np.dot(a,a.T))

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ True  True]
 [False False]]
[[ 5 11]
 [11 25]]


🔹 Challenge B: Eigen Analysis
python
Copy
Edit
M = np.array([[2, 0],
              [0, 3]])
Get eigenvalues and eigenvectors

Verify for first vector: Mv == λv

Try diagonalization: P @ D @ P⁻¹ == M

In [ ]:
M = np.array([[2,0],[0,3]])
eigenvalues,eigenvectors = np.linalg.eig(M)
e_v = eigenvectors[:,0].copy()
print(e_v)
print(np.allclose(M@eigenvectors,eigenvalues*eigenvectors))
el=np.diag(eigenvalues)
print(np.allclose(((M@el)@ (np.linalg.inv(M))) ,M))


[1. 0.]
True
True
